=== xbujm001/semestralni_prace/bujalka_michal.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0" elementFormDefault="qualified">
	<xs:element name="konfigurace_kuki_TV">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="konto">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="jmeno"/>
							<xs:element type="xs:string" name="prijmeni"/>
							<xs:element type="xs:date" name="datum_narozeni"/>
							<xs:element type="xs:string" name="adresa"/>
							<xs:element type="xs:string" name="Kuki.ID"/>
							<xs:element type="xs:string" name="tarif"/>
							<xs:element name="zaplaceno">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="trueFalse">
																	<xs:attribute type="typAnoNe" name="byloPlaceno"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="zarizeni">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="set_top_box">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="verze_FW"/>
										<xs:element type="xs:float" name="verze_portalu"/>
										<xs:element type="macAdresa" name="MAC_adresa"/>
										<xs:element type="ipAdresa" name="IP_adresa"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="nastaveni">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="nastaveni_obrazu">
											<xs:complexType>
												<xs:sequence>
													<xs:element type="typCisloCislo" name="rozliseni"/>
													<xs:element type="typCisloCislo" name="pomer_zobrazeni"/>
													<xs:element type="typRozsahDoSta" name="jas"/>
													<xs:element type="typRozsahDoSta" name="kontrast"/>
													<xs:element type="typRozsahDoSta" name="sytost"/>
													<xs:element type="typRozsahDoSta" name="ostrost"/>
													<xs:element type="typRozsahDoSta" name="protisvetlo"/>
													<xs:element type="typAnoNe" name="obraz3D"/>
													<xs:element name="jazyk">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="trueFalse">
																	<xs:attribute type="typJazyk" name="jazykKuki"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
													<xs:element name="titulky">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="trueFalse">
																	<xs:attribute type="typAnoNe" name="zapnoutTitulky"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
													<xs:element name="vypnoutObrazovku">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="typAnoNe">
																	<xs:attribute type="typCasovac" name="casovac"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="nastaveni_zvuku">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="zvuk">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="trueFalse">
																	<xs:attribute type="typRozsahDoSta" name="obnovitZvukNa"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
													<xs:element type="typVyvazeni" name="vyvazeni"/>
													<xs:element type="typRozsahDoSta" name="basy"/>
													<xs:element type="typRozsahDoSta" name="vysky"/>
													<xs:element type="typAnoNe" name="siroke_stereo"/>
													<xs:element type="typAnoNe" name="podporad_Dolby_Digital"/>
													<xs:element type="typAnoNe" name="mikrofon"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="instalace_kanalu">
											<xs:complexType>
												<xs:sequence>
													<xs:element type="typRegion" name="region"/>
													<xs:element type="typSignal" name="signal"/>
													<xs:element type="typLazeni" name="lazeni"/>
													<xs:element type="typKladneCislo" name="pocet_kanalu"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="poradi_kanalu">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="pozice" maxOccurs="unbounded" minOccurs="0">
														<xs:complexType>
															<xs:sequence>
																<xs:element type="typKladneCislo" name="cislo_pozice"/>
																<xs:element type="xs:string" name="nazev_pozice"/>
															</xs:sequence>
															<xs:attribute type="trueFalse" name="rodicovskyZamek"/>
															<xs:attribute type="trueFalse" name="oblibeny"/>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="nahravani">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="zpetne_pretaceni">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute type="typAnoNe" name="povolitPretaceni"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
													<xs:element name="nahravani_do_SET-TOP_boxu">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute type="typAnoNe" name="povolitNahravani"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
													<xs:element name="videoteka_serialy">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute type="typAnoNe" name="povolitSledovaniSerialu"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
													<xs:element name="videoteka_filmy">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute type="typAnoNe" name="povolitSledovaniFilmu"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="trueFalse" name="id_zarizeni"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="trueFalse">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ipAdresa">
		<xs:restriction base="xs:string">
			<xs:pattern  value="(([2]?[0-5]?[0-5])|([0-1]?[0-9]?[0-9]))\.(([2]?[0-5]?[0-5])|([0-1]?[0-9]?[0-9]))\.(([2]?[0-5]?[0-5])|([0-1]?[0-9]?[0-9]))\.(([2]?[0-5]?[0-5])|([0-1]?[0-9]?[0-9]))" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="macAdresa">
		<xs:restriction base="xs:string">
			<xs:pattern  value="[0-9A-Fa-f][0-9A-Fa-f]:[0-9A-Fa-f][0-9A-Fa-f]:[0-9A-Fa-f][0-9A-Fa-f]:[0-9A-Fa-f][0-9A-Fa-f]:[0-9A-Fa-f][0-9A-Fa-f]:[0-9A-Fa-f][0-9A-Fa-f]" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="typCisloCislo">
		<xs:restriction base="xs:string">
			<xs:pattern  value="([0-9]+(x|:)[0-9]+)|default" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="typRozsahDoSta">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="100"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="typJazyk">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Cesky"/>
			<xs:enumeration value="Anglicky"/>
			<xs:enumeration value="Nemecky"/>
			<xs:enumeration value="Spanelsky"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="typRegion">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Cesko"/>
			<xs:enumeration value="Slovensko"/>
			<xs:enumeration value="Nemecko"/>
			<xs:enumeration value="Francie"/>
			<xs:enumeration value="Anglie"/>
			<xs:enumeration value="Nizozemsko"/>
			<xs:enumeration value="Belgie"/>
			<xs:enumeration value="Italie"/>
			<xs:enumeration value="Rakousko"/>
			<xs:enumeration value="Rusko"/>
			<xs:enumeration value="Ukrajina"/>
			<xs:enumeration value="Svedsko"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="typAnoNe">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Ano"/>
			<xs:enumeration value="Ne"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="typCasovac">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="7200"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="typVyvazeni">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="-50"/>
			<xs:maxInclusive value="50"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="typSignal">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Digitalni"/>
			<xs:enumeration value="Analogovy"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="typKladneCislo">
		<xs:restriction base="xs:integer"> 
			<xs:minInclusive value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="typLazeni">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Automaticke"/>
			<xs:enumeration value="Manualni"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== xbujm001/semestralni_prace/bujalka_michal.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<konfigurace_kuki_TV xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation="bujalka_michal.xsd">
	<konto>
		<jmeno>Michal</jmeno>
		<prijmeni>Bujalka</prijmeni>
		<datum_narozeni>1994-11-22</datum_narozeni>
		<adresa>Fejfarova 3, Praha 9</adresa>
		<Kuki.ID>a1203567</Kuki.ID>
		<tarif>Kuki 31</tarif>
		<zaplaceno byloPlaceno="Ano">1</zaplaceno>
	</konto>
	<zarizeni id_zarizeni="1">
		<set_top_box>
			<verze_FW>Kuki (6.3.9600)</verze_FW>
			<verze_portalu>20160616.000</verze_portalu> 
			<MAC_adresa>6c:3b:e5:86:f8:f2</MAC_adresa>
			<IP_adresa>192.168.150.9</IP_adresa>
		</set_top_box>
		<nastaveni>
			<nastaveni_obrazu>
				<rozliseni>1920x1080</rozliseni>
				<pomer_zobrazeni>default</pomer_zobrazeni>
				<jas>50</jas>
				<kontrast>100</kontrast>
				<sytost>60</sytost>
				<ostrost>70</ostrost>
				<protisvetlo>100</protisvetlo>
				<obraz3D>Ano</obraz3D>
				<jazyk jazykKuki="Cesky">1</jazyk> 									
				<titulky zapnoutTitulky="Ano">0</titulky>							
				<vypnoutObrazovku casovac="10">Ne</vypnoutObrazovku>
			</nastaveni_obrazu>
			<nastaveni_zvuku>
				<zvuk obnovitZvukNa="20">1</zvuk>
				<vyvazeni>0</vyvazeni>
				<basy>20</basy>
				<vysky>30</vysky>
				<siroke_stereo>Ne</siroke_stereo>
				<podporad_Dolby_Digital>Ano</podporad_Dolby_Digital>
				<mikrofon>Ano</mikrofon>
			</nastaveni_zvuku>
			<instalace_kanalu>
				<region>Cesko</region>	 								
				<signal>Digitalni</signal>
				<lazeni>Automaticke</lazeni>
				<pocet_kanalu>31</pocet_kanalu>
			</instalace_kanalu>
			<poradi_kanalu>
				<pozice rodicovskyZamek="0" oblibeny="1">
					<cislo_pozice>1</cislo_pozice>
					<nazev_pozice>ČT 1</nazev_pozice>
				</pozice>
				<pozice rodicovskyZamek="0" oblibeny="0">
					<cislo_pozice>2</cislo_pozice>
					<nazev_pozice>ČT 2</nazev_pozice>
				</pozice>
				<pozice rodicovskyZamek="0" oblibeny="0">
					<cislo_pozice>3</cislo_pozice>
					<nazev_pozice>ČT 24</nazev_pozice>
				</pozice>
				<pozice rodicovskyZamek="0" oblibeny="1">
					<cislo_pozice>4</cislo_pozice>
					<nazev_pozice>ČT Sport</nazev_pozice>
				</pozice>
				<pozice rodicovskyZamek="0" oblibeny="1">
					<cislo_pozice>5</cislo_pozice>
					<nazev_pozice>Nova</nazev_pozice>
				</pozice>
				<pozice rodicovskyZamek="0" oblibeny="1">
					<cislo_pozice>6</cislo_pozice>
					<nazev_pozice>Nova 2</nazev_pozice>
				</pozice>
				<pozice rodicovskyZamek="0" oblibeny="0">
					<cislo_pozice>7</cislo_pozice>
					<nazev_pozice>Nova CINEMA</nazev_pozice>
				</pozice>
				<pozice rodicovskyZamek="0" oblibeny="0">
					<cislo_pozice>8</cislo_pozice>
					<nazev_pozice>Nova GOLD</nazev_pozice>
				</pozice>
				<pozice rodicovskyZamek="0" oblibeny="0">
					<cislo_pozice>9</cislo_pozice>
					<nazev_pozice>Nova ACTION</nazev_pozice>
				</pozice>
				<pozice rodicovskyZamek="0" oblibeny="1">
					<cislo_pozice>10</cislo_pozice>
					<nazev_pozice>Prima</nazev_pozice>
				</pozice>
				<pozice rodicovskyZamek="0" oblibeny="0">
					<cislo_pozice>11</cislo_pozice>
					<nazev_pozice>Prima COOL</nazev_pozice>
				</pozice>
				<pozice rodicovskyZamek="0" oblibeny="0">
					<cislo_pozice>12</cislo_pozice>
					<nazev_pozice>Prima LOVE</nazev_pozice>
				</pozice>
				<pozice rodicovskyZamek="0" oblibeny="0">
					<cislo_pozice>13</cislo_pozice>
					<nazev_pozice>TA3</nazev_pozice>
				</pozice>
				<pozice rodicovskyZamek="0" oblibeny="0">
					<cislo_pozice>14</cislo_pozice>
					<nazev_pozice>Prima MAX</nazev_pozice>
				</pozice>
				<pozice rodicovskyZamek="0" oblibeny="1">
					<cislo_pozice>15</cislo_pozice>
					<nazev_pozice>Disney Channel</nazev_pozice>
				</pozice>
				<pozice rodicovskyZamek="1" oblibeny="0">
					<cislo_pozice>16</cislo_pozice>
					<nazev_pozice>Cinemax</nazev_pozice>
				</pozice>
				<pozice rodicovskyZamek="1" oblibeny="1">
					<cislo_pozice>17</cislo_pozice>
					<nazev_pozice>FilmBox</nazev_pozice>
				</pozice>
				<pozice rodicovskyZamek="0" oblibeny="1">
					<cislo_pozice>18</cislo_pozice>
					<nazev_pozice>EuroSport 1</nazev_pozice>
				</pozice>
				<pozice rodicovskyZamek="0" oblibeny="0">
					<cislo_pozice>19</cislo_pozice>
					<nazev_pozice>EuroSport 2</nazev_pozice>
				</pozice>
				<pozice rodicovskyZamek="0" oblibeny="1">
					<cislo_pozice>20</cislo_pozice>
					<nazev_pozice>Sport 1</nazev_pozice>
				</pozice>
				<pozice rodicovskyZamek="0" oblibeny="0">
					<cislo_pozice>21</cislo_pozice>
					<nazev_pozice>Sport 2</nazev_pozice>
				</pozice>
				<pozice rodicovskyZamek="1" oblibeny="0">
					<cislo_pozice>22</cislo_pozice>
					<nazev_pozice>AXN</nazev_pozice>
				</pozice>
				<pozice rodicovskyZamek="0" oblibeny="1">
					<cislo_pozice>23</cislo_pozice>
					<nazev_pozice>CNN</nazev_pozice>
				</pozice>
				<pozice rodicovskyZamek="0" oblibeny="1">
					<cislo_pozice>24</cislo_pozice>
					<nazev_pozice>BBC</nazev_pozice>
				</pozice>
				<pozice rodicovskyZamek="0" oblibeny="0">
					<cislo_pozice>25</cislo_pozice>
					<nazev_pozice>Discovery</nazev_pozice>
				</pozice>
				<pozice rodicovskyZamek="1" oblibeny="0">
					<cislo_pozice>26</cislo_pozice>
					<nazev_pozice>Spicy TV</nazev_pozice>
				</pozice>
				<pozice rodicovskyZamek="1" oblibeny="0">
					<cislo_pozice>27</cislo_pozice>
					<nazev_pozice>XXX</nazev_pozice>
				</pozice>
				<pozice rodicovskyZamek="1" oblibeny="1">
					<cislo_pozice>28</cislo_pozice>
					<nazev_pozice>Horror TV</nazev_pozice>
				</pozice>
				<pozice rodicovskyZamek="0" oblibeny="0">
					<cislo_pozice>29</cislo_pozice>
					<nazev_pozice>MTV</nazev_pozice>
				</pozice>
				<pozice rodicovskyZamek="0" oblibeny="1">
					<cislo_pozice>30</cislo_pozice>
					<nazev_pozice>Óčko TV</nazev_pozice>
				</pozice>
				<pozice rodicovskyZamek="0" oblibeny="0">
					<cislo_pozice>31</cislo_pozice>
					<nazev_pozice>Barrandov TV</nazev_pozice>
				</pozice>
			</poradi_kanalu>
			<nahravani>
				<zpetne_pretaceni povolitPretaceni="Ano">48 hodin</zpetne_pretaceni>
				<nahravani_do_SET-TOP_boxu povolitNahravani="Ano">50 hodin</nahravani_do_SET-TOP_boxu>
				<videoteka_serialy povolitSledovaniSerialu="Ano">6 mesicu</videoteka_serialy>
				<videoteka_filmy povolitSledovaniFilmu="Ano">6 mesicu</videoteka_filmy>
			</nahravani>
		</nastaveni>
	</zarizeni>    
</konfigurace_kuki_TV>
